In [1]:
l1=[3,5,7,9]
l2=[1,2,4,6]
r=l1+l2
print(r)

[3, 5, 7, 9, 1, 2, 4, 6]


In [3]:
import numpy as np
a=np.array(l1)
b=np.array(l2)
r=a+b
print(a)

[3 5 7 9]


In [19]:
l1=[[1,6,3,8,5],
[4,7,8,6,1],
[8,17,9,3,5]]
l2=[[2,4,5,9,1],
    [4,6,7,8,12],
        [3,19,1,4,9]]

In [20]:
import numpy as np
a=np.array(l1)
b=np.array(l2)
add=a+b
print(add)

[[ 3 10  8 17  6]
 [ 8 13 15 14 13]
 [11 36 10  7 14]]


In [21]:
print("Type of list1:", type(l1))
print("Type of array1:", type(a))

Type of list1: <class 'list'>
Type of array1: <class 'numpy.ndarray'>


In [22]:
import numpy as np
a=np.array(l1)
b=np.array(l2)
mul=a*b
print(mul)

[[  2  24  15  72   5]
 [ 16  42  56  48  12]
 [ 24 323   9  12  45]]


In [23]:
divide = a / b
print(divide)


[[0.5        1.5        0.6        0.88888889 5.        ]
 [1.         1.16666667 1.14285714 0.75       0.08333333]
 [2.66666667 0.89473684 9.         0.75       0.55555556]]


In [25]:
power = np.power(a, b)
print(power)

[[                  1                1296                 243
            134217728                   5]
 [                256              117649             2097152
              1679616                   1]
 [                512 2632489875535903793                   9
                   81             1953125]]


In [26]:
sin_values = np.sin(a)
log_values = np.log(a)
log2_values = np.log2(a)
exp_values = np.exp(a)
print("Sin values:", sin_values)
print("Log values:", log_values)
print("Log2 values:", log2_values)
print("Exponential values:", exp_values)

Sin values: [[ 0.84147098 -0.2794155   0.14112001  0.98935825 -0.95892427]
 [-0.7568025   0.6569866   0.98935825 -0.2794155   0.84147098]
 [ 0.98935825 -0.96139749  0.41211849  0.14112001 -0.95892427]]
Log values: [[0.         1.79175947 1.09861229 2.07944154 1.60943791]
 [1.38629436 1.94591015 2.07944154 1.79175947 0.        ]
 [2.07944154 2.83321334 2.19722458 1.09861229 1.60943791]]
Log2 values: [[0.         2.5849625  1.5849625  3.         2.32192809]
 [2.         2.80735492 3.         2.5849625  0.        ]
 [3.         4.08746284 3.169925   1.5849625  2.32192809]]
Exponential values: [[2.71828183e+00 4.03428793e+02 2.00855369e+01 2.98095799e+03
  1.48413159e+02]
 [5.45981500e+01 1.09663316e+03 2.98095799e+03 4.03428793e+02
  2.71828183e+00]
 [2.98095799e+03 2.41549528e+07 8.10308393e+03 2.00855369e+01
  1.48413159e+02]]
